// <auto-generated />
using System;
using App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(OltpDbContext))]
    partial class OltpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("HIGHSCHOOL_OLTP")
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Models.OLTP.ClassInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Day")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Period")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("TermId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TermId");

                    b.ToTable("Classes", "HIGHSCHOOL_OLTP");
                });

            modelBuilder.Entity("App.Models.OLTP.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Credits")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses", "HIGHSCHOOL_OLTP");
                });

            modelBuilder.Entity("App.Models.OLTP.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("HeadId")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("HeadId");

                    b.ToTable("Departments", "HIGHSCHOOL_OLTP");
                });

            modelBuilder.Entity("App.Models.OLTP.Enrollment", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("AttendanceRate")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Final")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("Grade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("WorkHabits")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)");

                    b.HasKey("StudentId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("Enrollments", "HIGHSCHOOL_OLTP");
                });

            modelBuilder.Entity("App.Models.OLTP.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Students", "HIGHSCHOOL_OLTP");
                });

            modelBuilder.Entity("App.Models.OLTP.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Teachers", "HIGHSCHOOL_OLTP");
                });

            modelBuilder.Entity("App.Models.OLTP.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("TermNumber")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Terms", "HIGHSCHOOL_OLTP");
                });

            modelBuilder.Entity("CourseCourse", b =>
                {
                    b.Property<Guid>("IsPrerequisiteForId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("PrerequisitesId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("IsPrerequisiteForId", "PrerequisitesId");

                    b.HasIndex("PrerequisitesId");

                    b.ToTable("CourseCourse", "HIGHSCHOOL_OLTP");
                });

            modelBuilder.Entity("DepartmentTeacher", b =>
                {
                    b.Property<Guid>("DepartmentsId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("TeachersId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("DepartmentsId", "TeachersId");

                    b.HasIndex("TeachersId");

                    b.ToTable("DepartmentTeacher", "HIGHSCHOOL_OLTP");
                });

            modelBuilder.Entity("App.Models.OLTP.ClassInstance", b =>
                {
                    b.HasOne("App.Models.OLTP.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.OLTP.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("App.Models.OLTP.Term", "Term")
                        .WithMany("Classes")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("App.Models.OLTP.Course", b =>
                {
                    b.HasOne("App.Models.OLTP.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("App.Models.OLTP.Department", b =>
                {
                    b.HasOne("App.Models.OLTP.Teacher", "Head")
                        .WithMany()
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Head");
                });

            modelBuilder.Entity("App.Models.OLTP.Enrollment", b =>
                {
                    b.HasOne("App.Models.OLTP.ClassInstance", "Class")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.OLTP.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CourseCourse", b =>
                {
                    b.HasOne("App.Models.OLTP.Course", null)
                        .WithMany()
                        .HasForeignKey("IsPrerequisiteForId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.OLTP.Course", null)
                        .WithMany()
                        .HasForeignKey("PrerequisitesId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DepartmentTeacher", b =>
                {
                    b.HasOne("App.Models.OLTP.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Models.OLTP.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Models.OLTP.ClassInstance", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("App.Models.OLTP.Department", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("App.Models.OLTP.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("App.Models.OLTP.Teacher", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("App.Models.OLTP.Term", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
